In [0]:
%pip install openpyxl

Python interpreter will be restarted.
Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2
Python interpreter will be restarted.

In [0]:
pip install pandas

Python interpreter will be restarted.
Requirement already satisfied: pandas in /databricks/python3/lib/python3.9/site-packages (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /databricks/python3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /databricks/python3/lib/python3.9/site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.18.5 in /databricks/python3/lib/python3.9/site-packages (from pandas) (1.21.5)
Requirement already satisfied: six>=1.5 in /databricks/python3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Python interpreter will be restarted.

In [0]:
pip install pyspark

Python interpreter will be restarted.
Collecting pyspark
  Downloading pyspark-3.4.1.tar.gz (310.8 MB)
Collecting py4j==0.10.9.7
  Downloading py4j-0.10.9.7-py2.py3-none-any.whl (200 kB)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py): started
  Building wheel for pyspark (setup.py): finished with status 'done'
  Created wheel for pyspark: filename=pyspark-3.4.1-py2.py3-none-any.whl size=311285411 sha256=57062f5f35cbf6e9b0de9214854778dec77f3727901b2d650c5b2b4c11d2f330
  Stored in directory: /root/.cache/pip/wheels/2b/9a/39/d8019ffbfb76a39433455e3d5799e94d3e3cae8f41229f6bf8
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.7 pyspark-3.4.1
Python interpreter will be restarted.

In [ ]:
#accessing file from BLOB
# Replace these with your Blob Storage credentials and container name
storage_account_name = "<your-storage-account-name>"
storage_account_access_key = "<your-storage-account-access-key>"
spark.conf.set("fs.azure.account.key."+storage_account_name+".blob.core.windows.net",storage_account_access_key)


source_file_path=f"wasbs://{container_name}@{storage_account_name}.blob.core.windows.net/project/Customer Call List.xlsx",
sampleDataFilePath = spark.read.format("com.crealytics.spark.excel") \
            .option("header", "true") \
            .load(source_file_path)

In [0]:
dbutils.fs.ls("/FileStore/tables")

Out[1]: [FileInfo(path='dbfs:/FileStore/tables/Customer_Call_List-1.xlsx', name='Customer_Call_List-1.xlsx', size=12692, modificationTime=1688885452000),
 FileInfo(path='dbfs:/FileStore/tables/Customer_Call_List.xlsx', name='Customer_Call_List.xlsx', size=12692, modificationTime=1688884874000)]

In [0]:
#if the file is available in dbfs file store ---sample data file path
sampleDataFilePath = 'dbfs:/FileStore/tables/Customer_Call_List.xlsx'

#flags required for reading the excel
isHeaderOn = 'true'
isInferSchemaOn = 'false'

#sheet address in excel
sample1Address = "'0'!A1"

#read excelfile
sample1DF = spark.read.format('com.crealytics.spark.excel') \
.option('header', isHeaderOn) \
.option('inferSchema', isInferSchemaOn) \
.option('treatEmptyValuesAsNulls', 'false') \
.option('dataAddress', sample1Address) \
.load(sampleDataFilePath)
display(sample1DF)

CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,TRUE
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,FALSE
1003,Walter,/White,7066950392,298 Drugs Driveway,N,null,TRUE
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,TRUE
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,TRUE
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,TRUE
1007,Jeff,Winger,null,1209 South Street,No,No,FALSE
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,FALSE
1009,Gandalf,null,N/a,123 Middle Earth,Yes,null,FALSE
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,TRUE
1011,Samwise,Gamgee,null,"612 Shire Lane, Shire",Yes,No,TRUE
1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,null,TRUE
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,FALSE
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,FALSE
1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,FALSE
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,FALSE
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,FALSE
1018,Clark,Kent,7066950392,3498 Super Lane,Y,null,TRUE
1019,Creed,Braton,N/a,N/a,N/a,Yes,TRUE
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,TRUE
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,TRUE

In [0]:
display(sample1DF)

CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,TRUE
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,FALSE
1003,Walter,/White,7066950392,298 Drugs Driveway,N,null,TRUE
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,TRUE
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,TRUE
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,TRUE
1007,Jeff,Winger,null,1209 South Street,No,No,FALSE
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,FALSE
1009,Gandalf,null,N/a,123 Middle Earth,Yes,null,FALSE
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,TRUE
1011,Samwise,Gamgee,null,"612 Shire Lane, Shire",Yes,No,TRUE
1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,null,TRUE
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,FALSE
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,FALSE
1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,FALSE
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,FALSE
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,FALSE
1018,Clark,Kent,7066950392,3498 Super Lane,Y,null,TRUE
1019,Creed,Braton,N/a,N/a,N/a,Yes,TRUE
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,TRUE
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,TRUE

In [0]:
#dropping duplicates in the DataFrame
df = sample1DF.drop_duplicates()
df

Out[3]: DataFrame[CustomerID: string, First_Name: string, Last_Name: string, Phone_Number: string, Address: string, Paying Customer: string, Do_Not_Contact: string, Not_Useful_Column: string]

In [0]:
display(df)

CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,TRUE
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,FALSE
1003,Walter,/White,7066950392,298 Drugs Driveway,N,null,TRUE
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,TRUE
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,TRUE
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,TRUE
1007,Jeff,Winger,null,1209 South Street,No,No,FALSE
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,TRUE
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,FALSE
1009,Gandalf,null,N/a,123 Middle Earth,Yes,null,FALSE
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,FALSE
1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,null,TRUE
1011,Samwise,Gamgee,null,"612 Shire Lane, Shire",Yes,No,TRUE
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,FALSE
1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,FALSE
1018,Clark,Kent,7066950392,3498 Super Lane,Y,null,TRUE
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,FALSE
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,FALSE
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,TRUE
1019,Creed,Braton,N/a,N/a,N/a,Yes,TRUE

In [0]:
#dropping a column in the DataFrame
df = df.drop('Not_Useful_Column')
df

Out[5]: DataFrame[CustomerID: string, First_Name: string, Last_Name: string, Phone_Number: string, Address: string, Paying Customer: string, Do_Not_Contact: string]

In [0]:
display(df)

CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
1003,Walter,/White,7066950392,298 Drugs Driveway,N,null
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
1007,Jeff,Winger,null,1209 South Street,No,No
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
1009,Gandalf,null,N/a,123 Middle Earth,Yes,null
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,null
1011,Samwise,Gamgee,null,"612 Shire Lane, Shire",Yes,No
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
1018,Clark,Kent,7066950392,3498 Super Lane,Y,null
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
1019,Creed,Braton,N/a,N/a,N/a,Yes

In [0]:
#Converting spark DataFrame to pandas DataFrame
spark.conf.set("spark.sql.execution.arrow.pyspark.enabled", "true")
df = df.select("*").toPandas()

In [0]:
#cleaning the Last_Name column
#df["Last_Name"] = df["Last_Name"].str.lstrip("/")
#df["Last_Name"] = df["Last_Name"].str.rstrip("_")
df["Last_Name"] = df["Last_Name"].str.strip("123._/")

In [0]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,None,1209 South Street,No,No
7,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
8,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
9,1009,Gandalf,None,N/a,123 Middle Earth,Yes,None
10,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,None
12,1011,Samwise,Gamgee,None,"612 Shire Lane, Shire",Yes,No
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1018,Clark,Kent,7066950392,3498 Super Lane,Y,None
16,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
17,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
18,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
19,1019,Creed,Braton,N/a,N/a,N/a,Yes

In [0]:
#importing regular exp
import re

In [0]:
#cleaning the phone number using regular exp, it replaces pipe(|),forwardslash(/),hiphen(-) with ''
df['Phone_Number'] = df['Phone_Number'].str.replace(r'[|\/\-]', '', regex=True)

In [0]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,None
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,None,1209 South Street,No,No
7,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No
8,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
9,1009,Gandalf,None,Na,123 Middle Earth,Yes,None
10,1013,Don,Draper,1235432345,2039 Main Street,Yes,N
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,None
12,1011,Samwise,Gamgee,None,"612 Shire Lane, Shire",Yes,No
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No
15,1018,Clark,Kent,7066950392,3498 Super Lane,Y,None
16,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N
17,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
18,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N
19,1019,Creed,Braton,Na,N/a,N/a,Yes

In [0]:
#here we used regular exp for formatting the phone number
# df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))
# df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: re.sub(r'(\d{3})(\d{3})(\d{4})', r'\1-\2-\3', str(x)))

In [0]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,None,1209 South Street,No,No
7,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
8,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
9,1009,Gandalf,None,,123 Middle Earth,Yes,None
10,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,None
12,1011,Samwise,Gamgee,None,"612 Shire Lane, Shire",Yes,No
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,None
16,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
17,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
18,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N
19,1019,Creed,Braton,,N/a,N/a,Yes

In [0]:
df["Phone_Number"] = df["Phone_Number"].replace('None','')

In [0]:
#derived a new column by spliting the existing column
df[["Street_Address", "State", "Zip_Code"]] = df["Address"].str.split(',',2, expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,None,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
8,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None,None
9,1009,Gandalf,None,,123 Middle Earth,Yes,None,123 Middle Earth,None,None
10,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,None,None
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,None,2394 Hogwarts Avenue,None,None
12,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,None,3498 Super Lane,None,None
16,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
17,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
18,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None
19,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None

In [0]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes','Y')

df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
8,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
10,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
12,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
16,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
17,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
18,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,
19,1019,Creed,Braton,,,,Y,,,

In [0]:

df=df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Yes,93 West Main Street,,
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Yes,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,No,1209 South Street,,
7,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,No,25th Main Street,New York,
8,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,,
9,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
10,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,No,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,,
15,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,3498 Super Lane,,
16,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
17,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,
18,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,
19,1019,Creed,Braton,,N/a,N/a,Yes,N/a,,

In [0]:
df = df.replace('N/a','')

In [0]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Yes,93 West Main Street,,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Yes,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,No,1209 South Street,,
7,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,No,25th Main Street,New York,
8,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,,
10,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
12,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,No,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,,
16,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
17,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,
18,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,
19,1019,Creed,Braton,,,,Yes,,,

In [0]:
#retaining the not to contact people
for x in df.index:
    if df.loc[x, "Do_Not_Contact"] in ['Y','']:
        df.drop(x, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
8,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
10,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
12,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
16,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
17,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
18,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [0]:
#dropping the rows, who's phone is null
for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace=True)

df

#Another way to drop null values
#df = df.dropna(subset="Phone_Number"), inplace=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
7,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
8,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
10,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
16,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
17,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
18,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [0]:
#For the final data we are reseting the inedx
df = df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
2,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
3,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
4,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
5,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
6,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [0]:
import pyspark
from pyspark.sql import SparkSession

In [0]:
spark = SparkSession.builder.getOrCreate()

In [0]:
spark_df = spark.createDataFrame(df)
spark_df
table_name = "Do_not_contact_info"
database_name = "default"

spark_df.write.format("delta").mode("overwrite").saveAsTable(f"{database_name}.{table_name}")

Out[44]: DataFrame[CustomerID: string, First_Name: string, Last_Name: string, Phone_Number: string, Address: string, Paying Customer: string, Do_Not_Contact: string, Street_Address: string, State: string, Zip_Code: string]

In [0]:
display(spark_df)

CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,